FROM golang:latest AS build
WORKDIR /go/src/github.com/dylankemp/A2RepoSeng468/
COPY . .

ENV CGO_ENABLED=0
RUN go build -o server .

FROM build AS development
RUN apt-get update \
    && apt-get install -y git
CMD ["go", "run", "main.go"]
#was 8000
FROM alpine:latest
EXPOSE 8080
COPY --from=build /go/src/github.com/dylankemp/A2RepoSeng468/src/backend /server
CMD ["/server"]